export enum EnumActionType {
  SET_TOKEN = "SET_TOKEN",
  DELETE_TOKEN = "DELETE_TOKEN",
  SET_USER = "SET_USER",
  DELETE_USER = "DELETE_USER",
  SET_DATE_RANGE = "SET_DATE_RANGE",
  SET_FOCUS_WALLET = "SET_FOCUS_WALLET",
  SET_FOCUS_TRANSACTION = "SET_FOCUS_TRANSACTION",
  SET_WALLET_LIST = "SET_WALLET_LIST",
  SET_UPDATE_SIGNAL = "SET_UPDATE_SIGNAL",
}
